# Generated by Django 5.0 on 2025-01-07 11:32

from django.db import migrations, models
import phonenumber_field.modelfields
import utils.media

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_phone_number_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=utils.media.get_profile_image_path),
        ),
    ]
