# Generated by Django 5.0 on 2025-01-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20250107_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='business_type',
            field=models.CharField(choices=[('RETAILER', 'Retailer'), ('WHOLESALER', 'Wholesaler'), ('RESTAURANT', 'Restaurant'), ('HOTEL', 'Hotel'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
