# Generated by Django 5.0 on 2025-01-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_buyerprofile_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='preferred_payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI'), ('CREDIT_CARD', 'Credit Card'), ('COD', 'Cash on Delivery'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=50),
        ),
    ]
