# Generated by Django 5.0 on 2025-01-08 05:37

from django.db import migrations

def set_default_values(apps, schema_editor):
    BuyerProfile = apps.get_model('accounts', 'BuyerProfile')
    for profile in BuyerProfile.objects.all():
        if not profile.business_type:
            profile.business_type = 'OTHER'
        if not profile.preferred_payment_method:
            profile.preferred_payment_method = 'BANK_TRANSFER'
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_buyerprofile_preferred_payment_method'),
    ]

    operations = [
        migrations.RunPython(set_default_values),
    ]
