# Generated by Django 5.0 on 2025-01-08 05:47

from django.db import migrations

def remove_duplicates(apps, schema_editor):
    BuyerProfile = apps.get_model('accounts', 'BuyerProfile')
    User = apps.get_model('accounts', 'User')
    
    # Get all users with buyer profiles
    for user in User.objects.filter(role='BUYER'):
        # Get all profiles for this user
        profiles = BuyerProfile.objects.filter(user=user)
        if profiles.count() > 1:
            # Keep the first profile and delete the rest
            first_profile = profiles.first()
            profiles.exclude(id=first_profile.id).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_set_default_buyer_profile_values'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates),
    ]
