# Generated by Django 5.0 on 2025-01-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_buyerprofile_city_buyerprofile_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SELLER', 'Seller'), ('BUYER', 'Buyer'), ('DELIVERY_BOY', 'Delivery Boy')], default='BUYER', max_length=15),
        ),
    ]
