# Generated by Django 5.0 on 2025-01-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_delivery_boy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
