# Generated by Django 5.0 on 2025-01-15 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='email',
        ),
        migrations.RemoveField(
            model_name='deliveryboy',
            name='name',
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='license_number',
            field=models.CharField(max_length=20),
        ),
    ]
