# Generated by Django 5.0 on 2025-01-15 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_delete_orderdelivery'),
        ('seller', '0002_remove_deliveryboy_email_remove_deliveryboy_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryBoy',
        ),
    ]
