# Generated by Django 5.0 on 2025-01-15 08:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('BIKE', 'Bike'), ('SCOOTER', 'Scooter'), ('CAR', 'Car'), ('VAN', 'Van')], max_length=10)),
                ('vehicle_number', models.CharField(max_length=15)),
                ('license_number', models.CharField(max_length=20)),
                ('aadhar_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Aadhar number must be 12 digits')])),
                ('pan_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z]{5}[0-9]{4}[A-Z]{1}$', 'Invalid PAN number format')])),
                ('current_location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('successful_deliveries', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_image', models.ImageField(upload_to='delivery_documents/licenses/')),
                ('aadhar_image', models.ImageField(upload_to='delivery_documents/aadhar/')),
                ('pan_image', models.ImageField(upload_to='delivery_documents/pan/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
