# Generated by Django 5.0 on 2025-01-15 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryprofile',
            name='aadhar_image',
        ),
        migrations.RemoveField(
            model_name='deliveryprofile',
            name='aadhar_number',
        ),
        migrations.RemoveField(
            model_name='deliveryprofile',
            name='pan_image',
        ),
        migrations.RemoveField(
            model_name='deliveryprofile',
            name='pan_number',
        ),
    ]
