# Generated by Django 5.0 on 2025-01-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remove_deliveryprofile_aadhar_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='last_status_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='current_location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='license_image',
            field=models.ImageField(default=None, upload_to='delivery_documents/licenses/'),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='license_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('BREAK', 'On Break'), ('OFFLINE', 'Not Available')], default='OFFLINE', max_length=10),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='vehicle_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='vehicle_type',
            field=models.CharField(choices=[('BIKE', 'Motorcycle/Scooter'), ('BICYCLE', 'Bicycle'), ('CAR', 'Car'), ('VAN', 'Van')], default='BIKE', max_length=10),
        ),
    ]
