# Generated by Django 5.0 on 2025-02-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryprofile_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryprofile',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_documents/id_proofs/'),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='id_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_profiles/'),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='success_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='vehicle_registration',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_documents/vehicle_registrations/'),
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='vehicle_verified',
            field=models.BooleanField(default=False),
        ),
    ]
