# Generated by Django 5.0 on 2025-02-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_deliveryprofile_address_deliveryprofile_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryprofile',
            options={'verbose_name': 'Delivery Profile', 'verbose_name_plural': 'Delivery Profiles'},
        ),
        migrations.AlterField(
            model_name='deliveryprofile',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_documents/licenses/'),
        ),
    ]
